spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    dynamic: true
    cache:
      connection:
        mode: channel
      channel:
        checkout-timeout: 5s